<footer class="footer" id="footer">
    <div class="footer-widgets">
        <div class="container">
            <div class="row">
       			<div class="col-sm-6 col-md-3">
                    <aside class="widget widget-footer widget-categories">
                        <div class="widget-title">
                            <h4>Primary School Classes</h4>
                        </div>
                        <ul>
                            <li class="cat-item cat-item-7">
                                <a href="javascript:;">Lower Pri Maths Tuition</a>
                            </li>
                            <li class="cat-item cat-item-8">
                                <a href="javascript:;">Lower Pri English Tuition</a>
                            </li>
                             <li class="cat-item cat-item-10">
                                <a href="javascript:;">Upper Pri Science Tuition</a>
                            </li>
                             <li class="cat-item cat-item-11">
                                <a href="javascript:;">Lower Pri Chinese Tuition</a>
                            </li>
                        </ul>
                    </aside>
                </div>
                
            	<div class="col-sm-6 col-md-3">
                    <aside class="widget widget-footer widget-categories">
                        <div class="widget-title">
                            <h4>Lower Secondary Classes</h4>
                        </div>
                        <ul>
                            <li class="cat-item cat-item-7">
                                <a href="javascript:;">Secondary Maths Tuition</a>
                            </li>
                            <li class="cat-item cat-item-8">
                                <a href="javascript:;">Secondary English Tuition</a>
                            </li>
                            <li class="cat-item cat-item-9">
                                <a href="javascript:;">Secondary Chinese Tuition</a>
                            </li>
                            <li class="cat-item cat-item-10">
                                <a href="javascript:;">All Lower Sec Tuition</a>
                            </li>
                        </ul>
                    </aside>
                </div>
                
            	<div class="col-sm-6 col-md-3">
                    <aside class="widget widget-footer widget-categories">
                        <div class="widget-title">
                            <h4>Upper Secondary Classes</h4>
                        </div>
                        <ul>
                            <li class="cat-item cat-item-7">
                                <a href="javascript:;">Secondary E / A Maths Tuition</a>
                            </li>
                            <li class="cat-item cat-item-8">
                                <a href="javascript:;">Secondary Physics Tuition</a>
                            </li>
                            <li class="cat-item cat-item-9">
                                <a href="javascript:;">Secondary Chemistry Tuition</a>
                            </li>
                            <li class="cat-item cat-item-10">
                                <a href="javascript:;">All Lower Sec Tuition</a>
                            </li>
                        </ul>
                    </aside>
                </div>
                
             	<div class="col-sm-6 col-md-3">
                    <aside class="widget widget-footer widget-categories">
                        <div class="widget-title">
                            <h4>Junior College Classes</h4>
                        </div>
                        <ul>
                            <li class="cat-item cat-item-7">
                                <a href="javascript:;">JC Maths Tuition</a>
                            </li>
                            <li class="cat-item cat-item-8">
                                <a href="javascript:;">JC Physics Tuition</a>
                            </li>
                            <li class="cat-item cat-item-9">
                                <a href="javascript:;">JC Chemistry Tuition</a>
                            </li>
                            <li class="cat-item cat-item-10">
                                <a href="javascript:;">All JC Group Tuition</a>
                            </li>
                        </ul>
                    </aside>
                </div>
                
                <div class="clearfix visible-sm"></div>
            </div>
        </div>
    </div>

    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                	<div class="widget widget-footer">
                        <h4>About Us</h4>
                        <p>We provide two ways to look for tuition in Singapore. <a href="/tuition-agency">Order a private tutor</a> to your house or (b) <a href="/">Join a group tuition</a> near your house.</p>
                        <ul class="social-links">
                            <li><a href="https://www.facebook.com/Gia-S%C6%B0-Express-1538944193101109/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                        </ul>
    
                        <p>2016 &copy; Gia Sư Express</p>
                    </div>
                </div>

            	<div class="col-sm-2">
            		<div class="widget widget-footer">
                    	<h4>For Students</h4>
                    	<ul>
                            <li>
                           		<a href="javascript:;">Find a Home Tutor</a>                                    </li>
                            <li>
                            	<a href="javascript:;">Find Piano / Violin / Music Tutor</a>
                        	</li>
                            <li>
                                <a href="javascript:;">Tuition Agency Service</a>
                            </li>
                            <li>
                                <a href="javascript:;">Tuition Agency Fees</a>
                            </li>
                             <li>
                                <a href="javascript:;">Tuition Groups around SG</a>
                            </li>
                   		</ul>
               		</div>
				</div>
                    

           		<div class="col-sm-2">
           			<div class="widget widget-footer">
                   		<h4>For Tutors</h4>
                     	<ul>
                            <li>
                                <a href="javascript:;">Login</a>
                            </li>
                            <li>
                                <a href="javascript:;">Academic Tutor Signup</a>
                            </li>
                            <li>
                                <a href="javascript:;">Music Tutor Signup</a>
                            </li>
                            <li>
                                <a href="javascript:;">Tuition Jobs Forum</a>
                            </li>
                 		</ul>
             		</div>
            	</div>
                
           		<div class="col-sm-2">
           			<div class="widget widget-footer">
                    	<h4>General</h4>
                    	<ul>
                            <li>
                                <a href="javascript:;">About</a>
                            </li>
                            <li>
                                <a href="javascript:;">Contact Us</a>
                            </li><li>
                                <a href="javascript:;">Be a Coordinator</a>
                            </li>
    
                            <li>
                                <a href="javascript:;">Tuition Centers Login</a>
                            </li>
    
                            <li>
                                <a href="javascript:;">Terms &amp; Conditions</a>
                            </li>
                        </ul>
                    </div>
				</div>
			</div>
        </div>

        <div id="back-top">
            <a href="javascript:;">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>
    </div>
</footer>