<?php 
$this->headTitle()->prepend('Đổi mật khẩu') 
?>

<div class="row">
	<div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
		<div class="panel panel-condensed panel-default margin-top-30">
			<div class="panel-heading">
                <h3 class="panel-title">
                    <i class="fa fa-lock"></i> Đổi mật khẩu
                </h3>
            </div>
			<div class="panel-body">
			<?php if ($status === true) : ?>
			<div class="note note-success note-bordered">
	            <?php echo $this->translate('Đổi mật khẩu thành công.'); ?>
	        </div>
			<?php elseif ($status === false) : ?>
			<div class="note note-danger note-bordered">
	            <?php echo $this->translate('Không thể đổi mật khẩu. Vui lòng kiểm tra lại.'); ?>
	        </div>
			<?php endif; ?>
			<?php
			$form = $this->changePasswordForm;
			
			$form->prepare();
			$form->setAttribute('action', $this->url('zfcuser/changepassword'));
			$form->setAttribute('method', 'post');
			$form->setAttribute('class', 'form-horizontal');
			$form->setAttribute('role', 'form');
			$emailElement = $form->get('identity');
			$emailElement->setValue($this->zfcUserIdentity()->getEmail());
			
			echo $this->form()->openTag($form);								
			?>
			<div class="form-body">
			<div class="form-group <?php echo count($form->get('credential')->getMessages()) > 0 ? 'has-error' : '' ?>">
    			<?php echo $this->formLabel($form->get('credential')); ?>
    			<div class="col-lg-8">
    				<?php echo $this->formElement($form->get('credential')); ?>
    				<?php echo $this->formElementErrors()
								->setMessageOpenFormat('<div class="help-block">')
        						->setMessageSeparatorString('</div><div class="help-block">')
        						->setMessageCloseString('</div>')
        						->render($form->get('credential')); ?>
	    			</div>
    			</div>
				<div class="form-group <?php echo count($form->get('newCredential')->getMessages()) > 0 ? 'has-error' : '' ?>">
    			<?php echo $this->formLabel($form->get('newCredential')); ?>
    			<div class="col-lg-8">
    				<?php echo $this->formElement($form->get('newCredential')); ?>
    				<?php echo $this->formElementErrors($form->get('newCredential')); ?>
	    			</div>
				</div>
				<div class="form-group <?php echo count($form->get('newCredentialVerify')->getMessages()) > 0 ? 'has-error' : '' ?>">
    			<?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
    			<div class="col-lg-8">
    				<?php echo $this->formElement($form->get('newCredentialVerify')); ?>
    				<?php echo $this->formElementErrors($form->get('newCredentialVerify')); ?>
	    			</div>
				</div>
				<?php echo $this->formElement($form->get('identity')); ?>
				<?php if ($this->redirect): ?>
				<input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
				<?php endif ?>
			</div>
			<div class="form-actions">
				<div class="row">
					<div class="col-md-offset-2 col-md-8">
						<button type="submit" class="btn btn-primary">Save Change</button>
					</div>
				</div>
			</div>
			<?php echo $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>