<?php 
$facebook = $this->url('scn-social-auth-user/login/provider', ['provider' => 'facebook']);

if($this->redirect) {
    $formUrl = $this->url('zfcuser/login-ajax', [], [
		'query' => [
		    'redirect' => $this->escapeHtml($this->redirect)
		],
    ]);
} else {
    $formUrl = $this->url('zfcuser/login-ajax');
}
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $formUrl);
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('id', 'ajaxLoginForm');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
$form->prepare();
?>

<div class="modal-header no-border">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
</div>
<div class="modal-body padding-left-40 padding-right-40">
	<div class="text-center">
		<img src="<?php echo $this->basePath('img/logo.png') ?>" class="logo">
		
		<a href="<?php echo $facebook ?>" class="btn btn-block btn-facebook sbold fs-15 margin-top-15 margin-bottom-15">
			<i class="fa fa-facebook fs-20"></i> Đăng nhập bằng Facebook
		</a>
		<div class="input-or-separator margin-bottom-10">
			<div class="row row-m-5">
				<div class="col-p-5 col-xs-5"><hr></div>
				<div class="col-p-5 col-xs-2">
					<div class="input-or">hoặc</div>
				</div>
				<div class="col-p-5 col-xs-5"><hr></div>
			</div>
		</div>
		<?php echo $this->form()->openTag($form) ?>
        <?php echo $this->formElement($form->get('_token')); ?>
        <fieldset>
			<div class="form-group">
				<div class="input-icon">
					<i class="fa fa-envelope"></i>
					<?php echo $this->formElement($form->get('identity')); ?>
				</div>
			</div>
			<div class="form-group">
				<div class="input-icon">
					<i class="fa fa-lock"></i>
					<?php echo $this->formElement($form->get('credential')); ?>
				</div>
			</div>
			<div class="margin-top-10 margin-bottom-10">
				<button type="submit" class="btn btn-lg btn-block btn-primary sbold uppercase">Đăng nhập</button>
			</div>
			<p class="margin-bottom-0">Chưa có tài khoản? <a href="<?php echo $this->url('zfcuser/register') ?>" data-target="#modal_signup" data-toggle="modal" data-dismiss="modal">Đăng ký</a></p>
		</fieldset>
		<hr class="margin-top-10 margin-bottom-10">
		<p class="text-hint text-center fs-13">Chúng tôi tôn trọng sự riêng tư của bạn, GiaSưExpress.com không chia sẻ địa chỉ email hay các thông tin cá nhân của bạn với bên thứ ba mà không có sự đồng ý của bạn. Xem thêm <a class="text-nowrap" href="javascript:;" target="_blank">Chính sách bảo mật</a>.</p>
        <?php echo $this->form()->closeTag() ?>
	</div>		
</div>
<div class="modal-footer padding-left-40 padding-right-40 bg-grey">	
	<div class="text-center sbold">
		Bạn là gia sư ? <a href="<?php echo $this->url('zfcuser/register-tutor') ?>" data-target="#modal_become_tutor" data-toggle="modal" data-dismiss="modal">Đăng ký làm gia sư!</a>
	</div>
</div>