<?php
$facebook = $this->url('scn-social-auth-user/login/provider', ['provider' => 'facebook']);

$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form ajaxRegisterForm');
$form->setAttribute('role', 'form');
?>
<div class="modal-header no-border">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
</div>
<div class="modal-body padding-left-40 padding-right-40 padding-top-0">
	<div class="text-center">
		<img src="<?php echo $this->basePath('img/logo.png') ?>" class="logo">
		<h3 class="margin-top-10 margin-bottom-20">Đăng ký để tìm kiếm và<br> liên hệ trực tiếp với gia sư.</h3>
		<a href="<?php echo $facebook ?>" class="btn btn-block btn-facebook sbold fs-15 margin-bottom-10">
			<i class="fa fa-facebook fs-20"></i> Đăng ký bằng Facebook
		</a>
		<div class="input-or-separator margin-bottom-10">
			<div class="row row-m-5">
				<div class="col-p-5 col-xs-5"><hr></div>
				<div class="col-p-5 col-xs-2">
					<div class="input-or">hoặc</div>
				</div>
				<div class="col-p-5 col-xs-5"><hr></div>
			</div>
		</div>
	</div>
	<?php echo $this->form()->openTag($form) ?>
	<?php echo $this->formElement($form->get('_token')); ?>
    <fieldset class="text-left">
        <div class="form-group" data-for="display_name">
			<div class="input-icon">
				<i class="fa fa-user"></i>
				<?php echo $this->formElement($form->get('display_name')); ?>
			</div>
        </div>
        <div class="form-group" data-for="email">
        	<div class="input-icon">
        		<i class="fa fa-envelope"></i>
            	<?php echo $this->formElement($form->get('email')); ?>
            </div>
        </div>
        <div class="form-group" data-for="phone">
            <div class="input-icon">
        		<i class="fa fa-phone"></i>
            	<?php echo $this->formElement($form->get('mobilephone')); ?>
            </div>
        </div>
        <div class="form-group" data-for="password">
        	<div class="input-icon">
        		<i class="fa fa-lock"></i>
            	<?php echo $this->formElement($form->get('password')); ?>
            </div>
        </div>
        <div class="form-group" data-for="passwordVerify">
        	<div class="input-icon">
        		<i class="fa fa-key"></i>
            	<?php echo $this->formElement($form->get('passwordVerify')); ?>
            </div>
        </div>
    </fieldset>
    <div class="margin-top-10 margin-bottom-15">
    	<button type="submit" class="btn btn-lg btn-block btn-primary uppercase sbold">Đăng ký</button>
    </div>
	<p class="text-center">Đã có tài khoản? <a href="<?php echo $this->url('zfcuser/login-ajax') ?>" data-target="#modal_signin" data-toggle="modal" data-dismiss="modal">Đăng nhập</a></p>
	<p class="text-hint text-center fs-13">Khi chọn đăng ký tài khoản tại website của chúng tôi là bạn đã đọc và đồng ý với <a href="javascript:;" target="_blank">Điều khoản sử dụng</a>.</p>
	<hr class="margin-top-10 margin-bottom-10">
	<div class="checklist text-center fs-13">
		<?php echo $this->formrow($form->get('subscribe'), 'append', false) ?>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>
<div class="modal-footer padding-left-40 padding-right-40 bg-grey">	
	<div class="text-center sbold">
		Bạn là gia sư ? <a href="<?php echo $this->url('zfcuser/register-tutor') ?>" data-target="#modal_become_tutor" data-toggle="modal" data-dismiss="modal">Đăng ký làm gia sư!</a>
	</div>
</div>